name:                LiquidHaskell-tutorial
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/waddlaw/src-dir#readme
license:             BSD3
author:              shinya yamaguchi
maintainer:          ingroze@gmail.com
copyright:           Copyright (c) 2017 Shinya Yamaguchi
category:            Your Projects Category
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5

executables:
  src-dir:
    source-dirs:      src
    main:             Main.hs
